apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend
          image: ${IMAGE}
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: USER_SERVICE_URL
              value: "http://user-service:3000"
            - name: TODO_SERVICE_URL
              value: "http://todo-service:3001"
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: todo-app
spec:
  type: LoadBalancer
  loadBalancerIP: 35.189.12.21
  selector:
    app: frontend-service
  ports:
    - port: 3002
      targetPort: 3002
